name: Build container images

on: [push]

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

  base-image-build:
    name: compute-entrypoint:${{ matrix.repo }} image build
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    strategy:
      fail-fast: False
      matrix:
        repo: ['development', 'testing', 'release']
    steps:

    - uses: actions/checkout@v2

    - name: Cache base image
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: base-${{ matrix.repo }}-buildx-${{ github.sha }}

    - name: Generate tag list
      id: generate-tag-list
      env:
        REPO: ${{ matrix.repo }}
      run: |
        docker_repo=${GITHUB_REPOSITORY/opensciencegrid\/docker-/opensciencegrid/}
        echo "::set-output name=taglist::$docker_repo:$REPO"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2.2.2
      with:
        build-args: BASE_YUM_REPO=${{ matrix.repo }}
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"
        context: base
        cache-to: type=local,dest=/tmp/.buildx-cache

  child-image-builds:
    name: ${{ matrix.image }}:${{ matrix.repo }} image build
    runs-on: ubuntu-latest
    needs: [make-date-tag, base-image-build]
    if: startsWith(github.repository, 'opensciencegrid/')
    strategy:
      fail-fast: False
      matrix:
        repo: ['development', 'testing', 'release']
        image: ['hosted-ce', 'osg-ce-condor']
    steps:

    - uses: actions/checkout@v2

    - name: Load cached base image
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: base-${{ matrix.repo }}-buildx-${{ github.sha }}

    - name: Generate tag list
      id: generate-tag-list
      env:
        REPO: ${{ matrix.repo }}
        IMAGE: ${{ matrix.image }}
        TIMESTAMP: ${{ needs.make-date-tag.outputs.dtag }}
      run: |
        docker_repo=opensciencegrid/$IMAGE
        tag_list=$docker_repo:$REPO,$docker_repo:$REPO-$TIMESTAMP
        echo "::set-output name=taglist::$tag_list"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.2.2
      with:
        push: True
        build-args: BASE_YUM_REPO=${{ matrix.repo }}
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"
        context: ${{ matrix.image }}
        cache-from: type=local,src=/tmp/.buildx-cache
